services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: 'foo'
      POSTGRES_PASSWORD: "bar"
    ports:
      - "5432:5432"
  postgres_admin:
    image: adminer
    ports:
      - "8080:8080"
